arrowParens: 'always'
bracketSpacing: true
htmlWhitespaceSensitivity: 'ignore'
insertPragma: false
jsxSingleQuote: false
printWidth: 120
proseWrap: 'always'
quoteProps: 'as-needed'
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: none
useTabs: false
vueIndentScriptAndStyle: false

# printWidth: 100
# useTabs: false
# semi: true
# singleQuote: true
# trailingComma: 'all'
# bracketSpacing: true
# arrowParens: 'avoid'
# proseWrap: 'always'
