import '../sass/main.scss';
import './onclick-my_library';
import './modal.js';
import './get-genres-function.js';
import './get-popular-film.js';
import './team-members.js';
import './onFormSubmit.js';
import './scrollToTop.js';
import './addFilmsToLocalStorage.js';
import './get-watched.js';
import './get-queue.js';
import './toolbar.js'